version: "2"
services:
  varnish:
    image: varnish-service:1.0.0
    ports:
    - "8088:6081"
    - "6085:6085"
    depends_on:
    - anon
    - auth
    - download
    environment:
      CACHE_SIZE: "10G"
      BACKENDS_PORT: "8080"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"
      VARNISHNCSA_SUPERVISORD_ENABLED: "true"
  anon:
    image: eeacms/hello
    environment:
      PORT: "8080"
  auth:
    image: eeacms/hello
    environment:
      PORT: "8080"
  download:
    image: eeacms/hello
    environment:
      PORT: "8080"
