#!/bin/bash

source /etc/environment

python3 /dashboard_config.py
IPS_1=`cat /etc/varnish/env.backends`
python3 /add_backends.py env
IPS_2=`cat /etc/varnish/env.backends`

if [ "$IPS_1" != "$IPS_2" ]; then
  echo "ENV backends changed: $IPS_2"
  reload
fi
